// Root-level Gradle config.
// The key addition for Woosmap is the JitPack repository.
allprojects {
    repositories {
        google()
        mavenCentral()
        // Required to resolve the Woosmap Geofencing SDK.
        maven { url 'https://jitpack.io' }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
